from __future__ import annotations

ENABLE_DYNAMIC_WORD = False

THEME_CONFIG = {
    "page_title": "Irish Today — Learn a little, every day",
    "header_title": "Irish Today ☘️",
    "header_title_image": "daily_flyer/themes/irish_today_title.png",
    "header_subtitle": "Gaeilge - Irish history - sport - craic",
    "footer_text": "Built by Holtsnider Tech. Driven by Davy Holden History.",
}


WORDS = [
    {"native_text": "Craic", "pronunciation": "crack", "english": "Fun / good times / banter"},
    {"native_text": "Sláinte", "pronunciation": "slawn-cha", "english": "Health! / Cheers!"},
    {"native_text": "Fáilte", "pronunciation": "fawl-cha", "english": "Welcome"},
    {"native_text": "Gaeilge", "pronunciation": "gwayl-geh", "english": "Irish (language)"},
    {"native_text": "Dia dhuit", "pronunciation": "dee-ah gwit", "english": "Hello"},
    {"native_text": "Le do thoil", "pronunciation": "leh duh hull", "english": "Please"},
    {"native_text": "Go raibh maith agat", "pronunciation": "guh rev mah ah-gut", "english": "Thank you"},
    {"native_text": "Slán", "pronunciation": "slawn", "english": "Goodbye"},
    {"native_text": "Maidin mhaith", "pronunciation": "ma-jin wah", "english": "Good morning"},
    {"native_text": "Oíche mhaith", "pronunciation": "ee-hah wah", "english": "Good night"},
    {"native_text": "Tá sé go hálainn", "pronunciation": "taw shay guh haw-linn", "english": "It’s beautiful"},
    {"native_text": "Éire", "pronunciation": "air-uh", "english": "Ireland"},
    {"native_text": "Baile", "pronunciation": "bal-yeh", "english": "Home / town"},
    {"native_text": "Clann", "pronunciation": "clown", "english": "Family / children"},
    {"native_text": "Cairde", "pronunciation": "car-juh", "english": "Friends"},
    {"native_text": "Grá", "pronunciation": "graw", "english": "Love"},
    {"native_text": "Ceol", "pronunciation": "kyole", "english": "Music"},
    {"native_text": "Amhrán", "pronunciation": "ow-rawn", "english": "Song"},
    {"native_text": "Bia", "pronunciation": "bee-ah", "english": "Food"},
    {"native_text": "Uisce", "pronunciation": "ish-ka", "english": "Water"},
    {"native_text": "Arán", "pronunciation": "uh-rawn", "english": "Bread"},
    {"native_text": "Bainne", "pronunciation": "bahn-yeh", "english": "Milk"},
    {"native_text": "Tae", "pronunciation": "tay", "english": "Tea"},
    {"native_text": "Caife", "pronunciation": "kah-feh", "english": "Coffee"},
    {"native_text": "Teach", "pronunciation": "chockh", "english": "House"},
    {"native_text": "Bóthar", "pronunciation": "boh-her", "english": "Road"},
    {"native_text": "Scoil", "pronunciation": "skull", "english": "School"},
    {"native_text": "Leabhar", "pronunciation": "lyow-er", "english": "Book"},
    {"native_text": "Obair", "pronunciation": "ub-ir", "english": "Work"},
    {"native_text": "Madra", "pronunciation": "mod-rah", "english": "Dog"},
    {"native_text": "Cat", "pronunciation": "kot", "english": "Cat"},
    {"native_text": "Fear", "pronunciation": "far", "english": "Man"},
    {"native_text": "Bean", "pronunciation": "ban", "english": "Woman"},
    {"native_text": "Mór", "pronunciation": "more", "english": "Big"},
    {"native_text": "Beag", "pronunciation": "byag", "english": "Small"},
    {"native_text": "Inniu", "pronunciation": "in-yoo", "english": "Today"},
    {"native_text": "Inné", "pronunciation": "in-yay", "english": "Yesterday"},
    {"native_text": "Amárach", "pronunciation": "uh-maw-rukh", "english": "Tomorrow"},
    {"native_text": "Anois", "pronunciation": "uh-nish", "english": "Now"},
    {"native_text": "Grian", "pronunciation": "gree-an", "english": "Sun"},
    {"native_text": "Báisteach", "pronunciation": "bawsh-chakh", "english": "Rain"},
    {"native_text": "Farraige", "pronunciation": "far-ig-eh", "english": "Sea"},
    {"native_text": "Sléibhte", "pronunciation": "shlayv-tyeh", "english": "Mountains"},
    {"native_text": "Samhradh", "pronunciation": "sow-ruh", "english": "Summer"},
    {"native_text": "Geimhreadh", "pronunciation": "giv-ruh", "english": "Winter"},
    {"native_text": "Athbhliain", "pronunciation": "ah-vlee-in", "english": "New Year"},
    {"native_text": "Lá", "pronunciation": "law", "english": "Day"},
    {"native_text": "Oíche", "pronunciation": "ee-ha", "english": "Night"},
    {"native_text": "Míle fáilte", "pronunciation": "mee-leh fawl-cha", "english": "A hundred thousand welcomes"},
    {"native_text": "Go hiontach", "pronunciation": "guh hun-takh", "english": "Excellent / wonderful"},
]


PHRASES = [
    {"native_text": "Cad é mar atá tú?", "pronunciation": "cod ay mar a-taw too?", "english": "How are you?"},
    {"native_text": "Tá ocras orm.", "pronunciation": "taw uk-rus ur-im", "english": "I’m hungry."},
    {"native_text": "An féidir leat cabhrú liom?", "pronunciation": "on fay-der lat cow-roo lum?", "english": "Can you help me?"},
    {"native_text": "Ádh mór!", "pronunciation": "aww more", "english": "Good luck!"},
    {"native_text": "Go n-éirí an bóthar leat.", "pronunciation": "guh ny-ree on boh-her lat", "english": "May the road rise to meet you."},
    {"native_text": "Seo é!", "pronunciation": "shuh ay", "english": "Here it is! / That’s it!"},
]


HISTORY_THIS_DAY = {
    "03-17": "St. Patrick’s Day is celebrated each year on 17 March. It grew from a religious feast day into the most widely recognized global celebration of Irish identity.",
    "04-24": "1916 — The Easter Rising began in Dublin. Its immediate military effect was limited, but its political significance became enormous.",
    "06-16": "Bloomsday is observed on 16 June in honor of James Joyce’s Ulysses. It reflects Dublin’s unusually deep connection to literature and place.",
    "12-06": "1922 — The Irish Free State officially came into existence. It marked a major constitutional turning point in modern Irish history.",
}

HISTORY_WEEK_EVENTS = [
    {
        "month": 1,
        "day": 21,
        "title": "This Week in Irish History",
        "body": "1919 — Dáil Éireann first convened in Dublin around this week, marking a major step in the movement for Irish self-government.",
    },
    {
        "month": 2,
        "day": 1,
        "title": "This Week in Irish History",
        "body": "Saint Brigid’s Day falls around this week. The date is associated with one of Ireland’s most enduring saints and with older seasonal traditions marking the start of spring.",
    },
    {
        "month": 3,
        "day": 17,
        "title": "This Week in Irish History",
        "body": "St. Patrick’s Day falls around this week. Over time it became the best-known worldwide expression of Irish heritage and identity.",
    },
    {
        "month": 4,
        "day": 24,
        "title": "This Week in Irish History",
        "body": "1916 — The Easter Rising began around this week in Dublin. Though brief, it became one of the defining moments in modern Irish history.",
    },
    {
        "month": 6,
        "day": 16,
        "title": "This Week in Irish History",
        "body": "Bloomsday falls around this week and celebrates James Joyce’s Ulysses. Few cities are tied to a single literary work as strongly as Dublin is to that novel.",
    },
]


DID_YOU_KNOW = [
    "Newgrange predates Stonehenge and the Egyptian pyramids by centuries. Its winter solstice alignment shows that prehistoric builders in Ireland combined engineering skill with ceremonial design.",
    "Knowth and Dowth are major prehistoric monuments in the Boyne Valley. The concentration of ancient tombs there shows that this region was an important ceremonial landscape thousands of years ago.",
    "The Céide Fields in County Mayo are among the oldest known field systems in the world. Their preserved walls offer rare evidence of how Neolithic farming communities organized land.",
    "Poulnabrone Dolmen in the Burren is one of Ireland’s best-known portal tombs. Its stark limestone setting makes it a vivid reminder of Ireland’s prehistoric past.",
    "Carrowmore in County Sligo contains one of the largest collections of megalithic tombs in Ireland. The site suggests that the northwest was a major center of prehistoric ritual activity.",
    "Many Irish passage tombs were built to interact with light at specific times of year. These alignments hint at a deep interest in seasons, cycles, and the movement of the sun.",
    "Ogham is an early medieval alphabet used primarily to write the early Irish language. Most surviving inscriptions are carved on stone and often record personal names.",
    "Early Irish society was shaped in part by Brehon Law, a native legal tradition. These laws dealt with status, property, injury, and contracts in striking detail.",
    "Kingship in early Ireland was usually regional rather than national. Power often depended on alliances, tribute, and military strength rather than a single centralized state.",
    "The Hill of Tara is traditionally associated with the High Kings of Ireland. Its symbolic importance far exceeds its size because it became linked with ideas of sacred authority.",
    "The Rock of Cashel was once a royal site before becoming a major ecclesiastical center. Its surviving buildings show how political and religious power could overlap in medieval Ireland.",
    "St. Patrick is traditionally associated with bringing Christianity to Ireland in the 5th century. The spread of Christianity was gradual, but Patrick became the island’s most famous saint.",
    "St. Brigid of Kildare became one of Ireland’s best-known saints. Her legacy blends early Christian tradition with older seasonal customs and folk memory.",
    "Irish monasteries became important centers of learning in the early medieval period. They preserved texts, trained scholars, and helped connect Ireland to wider Christian Europe.",
    "Clonmacnoise grew into one of the most important monastic settlements in Ireland. Its location on the River Shannon helped make it a major crossroads of religion, trade, and learning.",
    "Glendalough developed from an early monastic settlement in County Wicklow. Its round tower and stone churches still reflect the spiritual prestige of the site.",
    "Skellig Michael off the Kerry coast once held an early Christian monastery. Its remote location shows how some monks sought isolation as part of religious life.",
    "The Book of Kells is a lavishly illuminated Gospel manuscript created around 800 AD. It is celebrated as a masterpiece of Insular art and medieval craftsmanship.",
    "The Book of Durrow is one of Ireland’s great early illuminated manuscripts. Its pages show how Irish monastic art developed rich decorative traditions long before modern printing.",
    "High crosses across Ireland combined Christian themes with detailed stone carving. They likely served as religious teaching tools as well as public monuments.",
    "Round towers were built at many Irish monastic sites. They probably functioned as bell towers, landmarks, and secure storage places.",
    "Dublin began as a Viking settlement before becoming Ireland’s largest city. Its origins as a trading port shaped its long-term political and economic importance.",
    "Waterford is widely regarded as Ireland’s oldest city. Its Viking roots remained visible even as it developed into a medieval port.",
    "Cork developed around an early monastic site and later became a major port. Its harbor connections played a major role in the city’s growth.",
    "Limerick became a significant settlement in the Viking age and later in medieval Ireland. Its position on the Shannon helped it thrive as a transport and trading center.",
    "Brian Boru is remembered as a powerful ruler who rose from Munster to become High King. Later tradition turned him into one of the most famous figures in Irish history.",
    "The Battle of Clontarf took place in 1014 near Dublin. It became a famous symbol of Irish resistance even though the real politics of the conflict were more complex.",
    "Medieval Ireland remained politically fragmented for much of its history. Rival kingdoms, church centers, and foreign powers all competed for influence.",
    "The Norman arrival in the 12th century reshaped Ireland through castles, towns, and new landholding systems. Norman influence spread unevenly, but it left a lasting mark on the landscape.",
    "Trim Castle in County Meath is one of the largest Norman castles in Ireland. Its scale reflects how military architecture was used to project control.",
    "Kilkenny became one of the strongest Norman urban centers in medieval Ireland. Its castle and street layout still reflect that heritage.",
    "Gaelic Irish culture remained strong for centuries after the Norman arrival. In many areas, local customs and the Irish language endured despite outside pressure.",
    "The Irish language was once the dominant everyday language across most of Ireland. Many modern place names still preserve older Irish meanings.",
    "Townlands are among the oldest surviving land divisions in Ireland. They often preserve local names and patterns of settlement that long predate modern maps.",
    "The Annals of the Four Masters preserve a sweeping record of Irish history as it was understood by early modern scholars. Even when used carefully, they remain an important source for the medieval past.",
    "The Flight of the Earls in 1607 is often seen as a turning point in the decline of the old Gaelic order. It symbolized the weakening of traditional aristocratic power.",
    "Penal Laws restricted many aspects of life for Catholics in later centuries. Their legacy remained powerful in Irish political memory long after the laws were relaxed.",
    "The Irish Parliament once sat in College Green in Dublin. It disappeared after the Act of Union in 1801 joined Ireland directly to the United Kingdom.",
    "Daniel O’Connell became famous for winning Catholic Emancipation in 1829. His huge public meetings showed how mass political organizing could reshape Irish life.",
    "The Great Famine caused catastrophic suffering in the 1840s. It transformed Ireland through hunger, disease, emigration, and lasting demographic decline.",
    "Ireland’s population fell dramatically after the Great Famine and did not quickly recover. The effects of that loss shaped family history, land use, and migration for generations.",
    "Irish emigrants carried music, politics, religion, and family networks across the world. Their influence helped make Irish identity global rather than purely local.",
    "Many people in the United States, Canada, Britain, and Australia trace ancestry to Ireland. Diaspora communities often preserved customs that changed over time in Ireland itself.",
    "The National School system, introduced in the 19th century, expanded access to formal education. It became one of the most influential institutions in everyday Irish life.",
    "The Ordnance Survey mapped Ireland in extraordinary detail during the 19th century. Its work helped standardize place names, boundaries, and modern geographical records.",
    "The Gaelic Revival renewed interest in the Irish language, folklore, literature, and traditional culture. It helped shape ideas of national identity before independence.",
    "The Gaelic League encouraged people to study and use Irish as a living language. Language activism became a major part of cultural nationalism.",
    "The GAA was founded in 1884 to support Irish games and cultural life. It played a major role in preserving and promoting hurling and Gaelic football.",
    "Hurling is often described as one of the oldest field sports in Europe. Its speed and deep local roots have made it central to Irish sporting identity.",
    "Camogie developed as the women’s game closely related to hurling. It became an important part of community and county sporting life.",
    "Gaelic football grew into one of Ireland’s most widely played and watched sports. County rivalries turned it into a major part of local identity.",
    "Croke Park is one of the largest stadiums in Europe. It is closely associated with the history and prestige of Gaelic games.",
    "The Abbey Theatre in Dublin played a defining role in the Irish literary revival. It gave writers and audiences a national stage for modern drama.",
    "W.B. Yeats helped found the Abbey Theatre and later won the Nobel Prize in Literature. His career linked Irish mythology, politics, and modern poetry.",
    "Lady Gregory was a central figure in Irish literary and theatrical life. Her work behind the scenes was crucial to the success of the Irish dramatic movement.",
    "Douglas Hyde helped lead the language revival before becoming Ireland’s first president. His public life linked culture, scholarship, and statehood.",
    "The Easter Rising of 1916 became a major symbolic moment in the struggle for independence. Its military outcome was limited, but its political impact was enormous.",
    "The Proclamation of the Irish Republic was read outside the General Post Office during the 1916 Rising. The document later became one of the most famous texts in modern Irish history.",
    "The Irish War of Independence was fought from 1919 to 1921. It forced a political crisis that changed the future of the island.",
    "The Anglo-Irish Treaty created the Irish Free State in 1922. It settled one conflict while opening a deep split over the terms of independence.",
    "The Irish Civil War left a deep mark on politics in the new state. Divisions born in that conflict influenced political life for decades.",
    "The Irish Free State marked a major turning point in modern Irish history. It gave the new state control over its own institutions while leaving unresolved constitutional questions.",
    "Bunreacht na hÉireann came into effect in 1937. The constitution redefined the state and remains the foundation of Irish law and government.",
    "Ireland formally became a republic in 1949. That step clarified its constitutional status and symbolized a further break from British structures.",
    "The office of President of Ireland is largely ceremonial but highly symbolic. Presidents often shape the moral tone of public life through speech and example.",
    "Áras an Uachtaráin in Phoenix Park is the official residence of the President of Ireland. The building reflects how older estates were adapted to serve the modern state.",
    "Phoenix Park is one of the largest enclosed public parks in any European capital city. It contains official residences, monuments, and broad spaces that make it central to Dublin life.",
    "Leinster House was once a ducal residence before becoming the home of parliament. Its reuse reflects the way older institutions were folded into the modern state.",
    "Ireland remained officially neutral during the Second World War, a period known domestically as 'The Emergency.' Neutrality became one of the defining features of Irish policy in that era.",
    "Ireland joined the European Economic Community in 1973. Membership deepened ties with Europe and helped reshape the economy over time.",
    "European Union membership played a major role in modernizing Irish infrastructure and trade. It changed how Ireland positioned itself in international affairs.",
    "The term 'Celtic Tiger' refers to the period of rapid economic growth in the late 20th and early 21st centuries. It transformed expectations about work, migration, and prosperity.",
    "Ireland experienced a severe financial crisis after the boom years of the Celtic Tiger. The contrast between rapid growth and sudden collapse remains a major lesson in modern economic history.",
    "St. Patrick’s Day began as a religious feast day. It later grew into a worldwide celebration of Irish identity and heritage.",
    "The Irish diaspora is much larger than the population of Ireland itself. That global spread helps explain why Irish culture has such a broad international reach.",
    "Traditional Irish music sessions keep tunes alive through shared performance rather than strict formal instruction. They make music a social practice as much as an art form.",
    "The fiddle, tin whistle, uilleann pipes, bodhrán, and accordion are all strongly associated with Irish traditional music. Each instrument contributes to the distinct sound of many local styles.",
    "Uilleann pipes differ from Scottish Highland bagpipes in both sound and technique. They are played with bellows and are known for their expressive tonal range.",
    "Sean-nós singing is an old Irish vocal tradition known for ornamentation and flexible rhythm. Its style places strong emphasis on individual interpretation.",
    "Céilí dancing is a social dance tradition that brings people together in groups. It remains closely tied to festivals, schools, and community events.",
    "Irish step dance gained worldwide attention through shows like Riverdance. Its stage success introduced many international audiences to Irish dance traditions.",
    "The Fleadh Cheoil is one of the largest festivals of Irish traditional music. It brings together performers, learners, and listeners from across Ireland and abroad.",
    "The Irish word 'craic' refers to enjoyable talk, fun, and good company. Its popularity reflects the high value often placed on conversation and sociability.",
    "The Burren in County Clare is famous for its limestone landscape. Its unusual environment supports plant life more often associated with very different climates.",
    "The Shannon is the longest river in Ireland. Its route has shaped travel, trade, settlement, and regional identity for centuries.",
    "The River Lee flows through Cork City before reaching Cork Harbour. That geography helped the city develop as both an inland center and a maritime hub.",
    "Cork Harbour is one of the great natural harbors of the world. Its size and shelter gave it long-term strategic and commercial importance.",
    "The Aran Islands are closely associated with Irish-language life and distinctive local traditions. Their cultural image became important far beyond their size.",
    "The Blasket Islands are famous for memoirs written in Irish and English. Those books preserved a way of life that might otherwise have been lost.",
    "The Dingle Peninsula includes one of Ireland’s best-known Gaeltacht areas. It remains strongly associated with spoken Irish and regional cultural life.",
    "A Gaeltacht is a region where Irish is recognized as the community language. These areas play a central role in efforts to sustain everyday use of Irish.",
    "TG4 brought modern television to Irish-speaking audiences in a fresh and ambitious way. The channel helped show that Irish could thrive in contemporary media.",
    "Raidió na Gaeltachta has been a major force in Irish-language broadcasting since the 1970s. It gave Irish-speaking communities a national platform for news, music, and discussion.",
    "James Joyce set much of his work in Dublin with extraordinary detail. His writing turned the city into one of the most vividly mapped places in world literature.",
    "Bloomsday is celebrated each year on 16 June in honor of Joyce’s novel Ulysses. The event shows how a single book became woven into the cultural life of Dublin.",
    "Samuel Beckett was born in Dublin and later won the Nobel Prize in Literature. His work helped make Irish writing central to modern drama and fiction.",
    "Oscar Wilde was born in Dublin and became one of the most famous playwrights in the English language. His wit and social criticism still attract readers around the world.",
    "Bram Stoker, the author of Dracula, was born in Dublin. His most famous novel became one of the defining works of Gothic fiction.",
    "The Chester Beatty Library in Dublin holds a remarkable collection of manuscripts, books, and artworks. It is one of Ireland’s great cultural institutions despite being less famous than some major tourist sites.",
    "The harp has long served as a symbol of Ireland. It appears on official state imagery and connects modern identity to older musical tradition.",
]

# Backward-compatible alias while the theme evolves.
HISTORY_GENERAL = DID_YOU_KNOW


SPORTS_SPOTLIGHT = [
    "Hurling is often described by the GAA as the world’s fastest field sport. It is also one of the oldest field games in the world, with roots in Ireland stretching back thousands of years.",
    "Hurling is played with a wooden stick called a hurley and a small ball called a sliotar. The sport is famous for combining speed, skill, bravery, and hand-eye coordination in a way few games can match.",
    "Gaelic football blends kicking, catching, hand-passing, and solo running into one fast-moving game. Players can carry the ball for four steps before they must bounce it, solo it, or pass it on.",
    "Gaelic football and hurling are both governed by the GAA, one of Ireland’s most important sporting and cultural organizations. The association has helped preserve native Irish games while also building deep local pride through county and club competition.",
    "Ireland’s rugby team enjoyed a particularly strong run in the 21st century, winning Six Nations titles and completing Grand Slams in 2009, 2018, and 2023. Those achievements helped confirm Ireland as one of Europe’s modern rugby powers.",
    "Irish women’s rugby has also produced landmark achievements of its own. One of the most celebrated came in 2013, when Ireland won the Women’s Six Nations Grand Slam for the first time.",
    "Shamrock Rovers are widely recognized as the most successful club in the Republic of Ireland. Their history includes a record haul of League of Ireland titles and a long-standing place in Dublin football culture.",
    "Croke Park is the symbolic heart of Gaelic games and one of the largest stadiums in Europe. With a capacity of 82,300, it hosts the biggest days in the Irish sporting calendar, especially the All-Ireland finals.",
    "The All-Ireland finals are not just championship games; they are major national occasions. Demand for tickets is famously intense, and the matches are followed by Irish audiences at home and abroad.",
    "The GAA’s reach extends far beyond Ireland itself. Irish emigrants helped bring Gaelic games to places such as the United States, Australia, Britain, Canada, China, and mainland Europe.",
    "Camogie is the women’s stick-and-ball game closely related to hurling, and it has a proud history of its own. The Camogie Association was founded in 1904, showing how deep the roots of women’s Irish sport run.",
    "Camogie is often introduced as hurling’s women’s counterpart, but it stands as a major sport in its own right. Its top inter-county matches are known for elite skill, fierce competition, and strong county identity.",
    "Boxing has been Ireland’s most successful Olympic sport by medal count. Irish boxing medals make up more than half of the country’s overall Olympic total, which says a lot about the sport’s place in Irish athletics.",
    "Rowing has become one of Ireland’s great modern success stories. Ireland won its first Olympic rowing medal in 2016, and the country later added Olympic golds and more podium finishes through crews that captured the public imagination.",
    "Horse racing is another huge part of Irish sporting life, especially in the jumps tradition. Punchestown is considered the home of Irish jump racing, and its spring festival is one of the biggest events on the national racing calendar.",
]


TRIVIA = [
    "The Irish flag’s green, white, and orange symbolize tradition, peace, and community identity.",
    "There are Gaeltacht regions where Irish remains the community’s everyday language.",
    "Halloween has roots in the Celtic festival Samhain.",
    "The Wild Atlantic Way is one of the world’s longest defined coastal routes.",
    "Irish harps appear on Irish coinage and the state seal.",
]


BACKGROUND_CADENCE = "daily"

BACKGROUNDS = [
    {
        "path": "daily_flyer/themes/irish_kilkenny_hurling_ai.png",
        "label": "Kilkenny Hurling Background",
    },
    {
        "path": "daily_flyer/themes/irish_celtic_knot_background.jpg",
        "label": "Irish Celtic Knot Background",
    },
    {
        "path": "daily_flyer/themes/irish_historic_map_background.jpg",
        "label": "Irish Historic Map Background",
    },
    {
        "path": "daily_flyer/themes/irish_misty_hills_background.jpg",
        "label": "Irish Misty Hills Background",
    },
]
