from __future__ import annotations

from html import escape

from daily_flyer.models import CardItem, PageContext
from daily_flyer.utils import resolve_date
from daily_flyer.themes import e46_owner_companion_v5 as visual_base

THEME_NAME = "nissan_z_2024"
THEME_CONFIG = {
    "page_title": "Garage Journey Workshop — 2024 Nissan Z Performance",
    "header_title": "NISSAN Z / RZ34",
    "header_subtitle": "Factory-grounded technical index for the 2024 Nissan Z Performance — VR30DDTT twin-turbo V6, driveline, chassis, brakes, electronics, and original Nissan references.",
    "footer_text": "Garage Journey technical reference. Confirm VIN, transmission, build data, options and modification state before applying configuration-specific procedures or parts.",
    "hero_kicker": "2024 // NISSAN Z PERFORMANCE // RZ34 // VR30DDTT",
    "hero_summary_pill": "SEARCH • SYSTEM • COMPONENT • SOURCE",
}

BROCHURE = "https://www.nissanusa.com/content/dam/Nissan/us/vehicle-brochures/2024/2024-nissan-nissan-z-brochure-en.pdf"
OWNER_MANUAL = "https://www.nissanusa.com/content/dam/Nissan/us/manuals-and-guides/nissan-z/2024/2024-nissan-z-owner-manual.pdf"
PARTS = "https://parts.nissanusa.com/v-2024-nissan-z"
MANUALS = "https://www.nissanusa.com/owners/manuals-guides.html"

SYSTEMS = [
    {"key":"engine","index":"VR30","title":"VR30DDTT / Boost-Air-Fuel","subtitle":"3.0L twin-turbo direct-injected V6","aliases":["engine","vr30","vr30ddtt","turbo","boost","intercooler","fuel","direct injection","intake"],"symptoms":["misfire","low boost","power loss","hesitation","rough idle","check engine","surge"],"primary":"VR30DDTT 3.0L twin-turbocharged V6","components":["Twin turbochargers / boost control","Water-cooled intercooler system","Direct injection / fuel delivery","Airflow / throttle control","Ignition / spark","Sensors / turbo-speed monitoring"],"facts":["400 hp @ 6,400 rpm","350 lb-ft @ 1,600–5,200 rpm","Twin turbochargers with direct gasoline injection","Water-cooled intercooler system","Rear-wheel-drive application in the Z"],"sources":[("2024 Nissan Z brochure",BROCHURE),("2024 Z owner's manual",OWNER_MANUAL),("Official Nissan parts catalog",PARTS)]},
    {"key":"cooling","index":"COOL","title":"Cooling / Lubrication","subtitle":"Engine coolant, charge cooling and oil systems","aliases":["cooling","coolant","radiator","water pump","thermostat","fan","oil","lubrication","heat exchanger","intercooler"],"symptoms":["overheat","runs hot","coolant leak","oil leak","temperature warning","heat soak"],"primary":"VR30 thermal-management and lubrication systems","components":["Engine cooling circuit","Radiator / fans","Water-cooled intercooler circuit","Engine oil system","Hoses / reservoirs","Temperature monitoring"],"facts":["The factory brochure explicitly identifies a water-cooled intercooler system","Turbocharged operation makes heat management central to repeatable performance","Exact fill and bleed procedures should follow Nissan service information"],"sources":[("2024 Nissan Z brochure",BROCHURE),("2024 Z owner's manual",OWNER_MANUAL),("Official Nissan parts catalog",PARTS)]},
    {"key":"transmission","index":"MT/AT","title":"Transmission / Clutch","subtitle":"6-speed manual or 9-speed automatic","aliases":["transmission","gearbox","manual","automatic","6 speed","9 speed","clutch","synchrorev","paddle"],"symptoms":["hard shift","gear grind","clutch slip","shift flare","shift delay","transmission noise"],"primary":"Performance trim transmission paths","components":["6-speed manual","Clutch / flywheel","SynchroRev Match","9-speed automatic","Paddle controls","Transmission cooling / fluid"],"facts":["Performance was offered with a 6-speed manual","A 9-speed automatic was also available","Transmission type belongs to the individual Garage vehicle profile"],"sources":[("2024 Nissan Z brochure",BROCHURE),("2024 Z owner's manual",OWNER_MANUAL),("Official Nissan parts catalog",PARTS)]},
    {"key":"driveline","index":"RWD","title":"Rear Driveline / LSD","subtitle":"RWD with mechanical limited-slip differential","aliases":["driveline","rear wheel drive","rwd","differential","lsd","limited slip","axle","halfshaft","driveshaft"],"symptoms":["clunk","vibration","wheel hop","differential noise","traction issue"],"primary":"Rear-wheel-drive Z Performance driveline","components":["Mechanical limited-slip differential","Propeller shaft","Rear halfshafts","Mounts / bushings","Wheel hubs","Traction / VDC interaction"],"facts":["Performance trim includes a mechanical limited-slip differential","Rear-wheel drive is core to the RZ34 Z layout","Launch-control availability depends on transmission/configuration"],"sources":[("2024 Nissan Z brochure",BROCHURE),("2024 Z owner's manual",OWNER_MANUAL),("Official Nissan parts catalog",PARTS)]},
    {"key":"chassis","index":"RZ34","title":"Chassis / Steering","subtitle":"Double-wishbone front, multi-link rear","aliases":["suspension","chassis","steering","double wishbone","multi link","shock","spring","alignment","stabilizer"],"symptoms":["pulling","clunk","wandering","alignment","uneven tire wear","steering feel"],"primary":"RZ34 suspension and electric power steering","components":["Double-wishbone front suspension","Multi-link rear suspension","Monotube shocks","Front strut brace","Stabilizer bars","Electric power steering / alignment"],"facts":["Double-wishbone front suspension","Multi-link rear suspension","Monotube shock absorbers","Vehicle-speed-sensitive electric power steering"],"sources":[("2024 Nissan Z brochure",BROCHURE),("2024 Z owner's manual",OWNER_MANUAL),("Official Nissan parts catalog",PARTS)]},
    {"key":"brakes","index":"AKE","title":"Brakes / Wheels / Tires","subtitle":"Performance Akebono brakes and RAYS forged wheels","aliases":["brakes","akebono","caliper","rotor","disc","wheel","rays","tire","abs"],"symptoms":["brake vibration","pedal","pad wear","rotor wear","tire wear","wheel vibration"],"primary":"Z Performance braking and wheel package","components":["4-piston front calipers","2-piston rear calipers","14.0-inch front rotors","13.8-inch rear rotors","19-inch RAYS forged wheels","Performance tires / TPMS"],"facts":["Akebono 4-piston front / 2-piston rear red-painted aluminum calipers","14.0-inch front and 13.8-inch rear vented discs","19 x 9.5 front / 19 x 10.0 rear RAYS forged wheels","255/40R19 front and 275/35R19 rear performance tires"],"sources":[("2024 Nissan Z brochure",BROCHURE),("2024 Z owner's manual",OWNER_MANUAL),("Official Nissan parts catalog",PARTS)]},
    {"key":"electrical","index":"ECM","title":"Electrical / Driver Controls","subtitle":"ECM, digital cluster, driver assists and diagnostics","aliases":["electrical","diagnostics","ecm","obd","battery","charging","cluster","infotainment","vdc","sensor"],"symptoms":["warning light","fault code","battery","no start","module","sensor","communication"],"primary":"Powertrain, body and driver-control electronics","components":["ECM / engine controls","OBD-II diagnostics","12.3-inch digital dashboard","NissanConnect / infotainment","VDC / ABS / driver assists","Battery / charging"],"facts":["12.3-inch digital dashboard is part of the Z cockpit","Performance trim integrates modern driver-assistance and infotainment systems","Exact module diagnosis/programming should follow Nissan service information"],"sources":[("2024 Nissan Z brochure",BROCHURE),("2024 Z owner's manual",OWNER_MANUAL),("Nissan manuals & guides",MANUALS)]},
]

ENGINE_COMPONENTS = [
    {"key":"turbos","title":"Twin Turbochargers / Boost Control","group":"BOOST","check":"Compare requested versus delivered boost, inspect intake/charge plumbing and verify sensor evidence before condemning turbo hardware.","adjacent":"Charge cooling, intake tract, exhaust, vacuum/pressure plumbing and calibration state.","facts":["The VR30DDTT uses twin turbochargers","Nissan highlights turbo-speed sensing and turbine design in the Z performance description","Modification/tune state materially changes boost diagnosis"]},
    {"key":"intercooler","title":"Water-Cooled Intercooler System","group":"CHARGE COOLING","check":"Verify coolant level, pump/circuit function, heat-exchanger condition and charge-temperature behavior before chasing a power-loss complaint.","adjacent":"Turbo outlets, intake manifold, cooling hoses and front heat-exchanger stack.","facts":["Nissan identifies a water-cooled intercooler system","Charge-temperature control is central to repeated boosted operation"]},
    {"key":"fuel","title":"Direct Injection / Fuel Delivery","group":"FUEL","check":"Use rail-pressure, trim and cylinder-specific evidence to separate fuel-supply, injector and ignition faults.","adjacent":"Tank supply, high-pressure system, injectors, EVAP, intake leaks and ignition.","facts":["Direct gasoline injection is part of the 400-hp VR30 package","Exact pressure tests belong in Nissan service information"]},
    {"key":"airflow","title":"Airflow / Throttle Control","group":"AIR","check":"Inspect intake integrity and compare airflow/pressure and throttle commanded-versus-actual data before replacing electronic components.","adjacent":"Air filters, intake tubes, charge plumbing, throttle bodies and boost sensors.","facts":["The twin-turbo system depends on coordinated airflow, pressure and throttle control","Intake modifications should be recorded with the individual Garage vehicle"]},
    {"key":"ignition","title":"Ignition / Spark","group":"IGNITION","check":"Use misfire counts, plug inspection and controlled component swaps before attributing a load misfire to boost or fueling.","adjacent":"Injectors, compression, fuel pressure, charge leaks and calibration state.","facts":["Turbocharged cylinder pressure makes plug condition especially relevant","Keep exact plug and service specifications tied to Nissan service information"]},
    {"key":"sensors","title":"Sensors / Turbo-Speed Monitoring","group":"CONTROL","check":"Correlate DTCs and live data across pressure, temperature and turbo-speed sensing before replacing hardware.","adjacent":"ECM, boost control, charge cooling, wiring/connectors and power/ground integrity.","facts":["Nissan specifically calls out turbo-speed sensors in the Z performance material","Sensor plausibility is more useful than parts-swapping"]},
]

FONT_HEAD = '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700;800;900&family=IBM+Plex+Mono:wght@500;600&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">'

EXTRA_CSS = visual_base.EXTRA_CSS + r'''
:root{--irish-green:#d6202f;--blue:#d6202f;--teal:#ff8f98;--gj-display:"Barlow Condensed","Arial Narrow",sans-serif;--gj-body:"Manrope",Arial,sans-serif;--gj-mono:"IBM Plex Mono",Consolas,monospace}
body{font-family:var(--gj-body);background:radial-gradient(circle at 82% 5%,rgba(214,32,47,.19),transparent 29rem),linear-gradient(rgba(8,9,12,.989),rgba(5,6,8,.999)),#07080a}.hero-wrap::before{height:3px;background:linear-gradient(90deg,#d6202f 0 40%,#f4f4f4 40% 57%,#35383c 57%)}
.hero h1,.e46-work-title,.e46-component-title{font-family:var(--gj-display);font-weight:800;letter-spacing:-.025em}.hero-kicker,.eyebrow,.e46-search-kicker,.e46-work-kicker,.e46-system-index,.e46-component-group,.e46-source-type,.e46-data-label{font-family:var(--gj-mono);color:#ff8f98}
.card{border-radius:28px 7px 28px 7px!important}.e46-system-grid{gap:14px;border:0!important}.e46-system{border:1px solid rgba(255,255,255,.11)!important;border-radius:20px 5px 20px 5px!important;background:linear-gradient(145deg,rgba(255,255,255,.042),rgba(255,255,255,.012))!important}.e46-system:hover,.e46-system:focus-visible{background:rgba(214,32,47,.11)!important;transform:translateY(-4px)}.e46-system h3{font-family:var(--gj-display);font-size:2rem}.e46-search-shell{border-radius:999px;border-color:rgba(255,143,152,.45);background:rgba(255,255,255,.035)}.e46-open,.e46-result-rank,.e46-component-open,.e46-component-back{color:#ff8f98!important}.e46-workshop,.e46-component-view{border-radius:24px 6px 24px 6px;overflow:hidden}.e46-work-details,.e46-component-details{background:linear-gradient(145deg,#15171b,#101114)}.e46-component-nav,.e46-source-strip{gap:10px;border:0!important}.e46-component-card,.e46-source-tile{border:1px solid rgba(255,255,255,.10)!important;border-radius:16px 4px 16px 4px!important;background:rgba(255,255,255,.018)}.e46-component-card:hover{background:rgba(214,32,47,.10)!important}.e46-home-specs{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;border:0;margin-bottom:28px}.e46-home-specs>div{padding:13px 14px;border:1px solid rgba(255,255,255,.09);border-radius:13px 4px 13px 4px;background:rgba(255,255,255,.016)}.e46-home-specs span{display:block;color:#848a93;font-family:var(--gj-mono);font-size:.56rem;font-weight:900;letter-spacing:.08em}.e46-home-specs strong{display:block;margin-top:7px;color:#fff;font-size:.82rem}.e46-fact-list{margin:18px 0 0;padding:0;list-style:none}.e46-fact-list li{padding:8px 0;border-top:1px solid rgba(255,255,255,.10);color:#c8cad2;font-size:.79rem}.e46-schematic-mark{color:#ff8f98}.card--nissan_workspace{display:none}.card--nissan_workspace.is-open{display:block}.gj-floatnav{position:fixed;z-index:120;top:14px;left:50%;transform:translateX(-50%);display:flex;gap:4px;padding:4px;border:1px solid rgba(255,143,152,.25);border-radius:999px;background:rgba(8,9,12,.78);backdrop-filter:blur(16px)}.gj-floatnav button{min-height:38px;padding:0 13px;border:0;border-radius:999px;background:transparent;color:#fff;font-family:var(--gj-mono);font-size:.61rem;font-weight:900;letter-spacing:.09em;text-transform:uppercase}.gj-floatnav button:hover{background:rgba(214,32,47,.18)}
@media(max-width:900px){.e46-home-specs{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.e46-home-specs{grid-template-columns:repeat(2,1fr)}.gj-floatnav{top:auto;bottom:calc(8px + env(safe-area-inset-bottom))}.e46-system-grid{grid-template-columns:1fr!important}.e46-system{min-height:160px}}
'''


def _pipes(items): return "|".join(items)
def _refs(sources): return ''.join(f'<a class="e46-ref" href="{escape(url,quote=True)}" target="_blank" rel="noopener noreferrer"><span>{escape(label)}</span><span>OPEN ↗</span></a>' for label,url in sources)
def _tile(s):
    attrs=f'data-key="{escape(s["key"])}" data-title="{escape(s["title"],quote=True)}" data-subtitle="{escape(s["subtitle"],quote=True)}" data-search="{escape(_pipes(s["aliases"]+s["symptoms"]+s["facts"]),quote=True)}" data-items="{escape(_pipes(s["components"]),quote=True)}" data-aliases="{escape(_pipes(s["aliases"]),quote=True)}" data-symptoms="{escape(_pipes(s["symptoms"]),quote=True)}"'
    return f'<button class="e46-system" type="button" {attrs}><div class="e46-system-image e46-schematic"><span class="e46-schematic-mark">{escape(s["index"])}</span></div><div class="e46-system-copy"><span class="e46-system-index">SYSTEM</span><h3>{escape(s["title"])}</h3><p>{escape(s["subtitle"])}</p><span class="e46-open">Open workshop →</span></div></button>'
def _system_template(s):
    comps=''.join(f'<span class="e46-component">{escape(x)}</span>' for x in s['components']); facts=''.join(f'<li>{escape(x)}</li>' for x in s['facts']); drill=''
    if s['key']=='engine': drill='<div class="e46-drill-label">Drill into VR30 boost / air / fuel</div><div class="e46-component-nav">'+''.join(f'<button class="e46-component-card" type="button" data-component="{c["key"]}"><span class="e46-component-group">{escape(c["group"])}</span><strong>{escape(c["title"])}</strong><span>{escape(c["check"].split(",")[0])}</span><span class="e46-component-open">→</span></button>' for c in ENGINE_COMPONENTS)+'</div>'
    return f'<template id="e46-template-{s["key"]}"><div class="e46-workshop"><div class="e46-visual"><div class="e46-visual-head"><span>{escape(s["primary"])}</span><span>Nissan factory-grounded reference</span></div><div class="e46-diagram"><div class="e46-diagram-placeholder">{escape(s["index"])}</div></div><div class="e46-source-credit">Use Nissan service information for exact VIN/configuration-specific procedures, torque values and diagnostics.</div></div><div class="e46-work-details"><span class="e46-work-kicker">2024 NISSAN Z PERFORMANCE / RZ34</span><h3 class="e46-work-title">{escape(s["title"])}</h3><p class="e46-work-primary">{escape(s["primary"])}</p><div class="e46-component-grid">{comps}</div><div class="e46-ref-actions">{_refs(s["sources"])}</div><div class="e46-data-block"><div class="e46-data-label">Pinned factory facts</div><ul class="e46-fact-list">{facts}</ul></div>{drill}</div></div></template>'
def _component_template(c):
    facts=''.join(f'<li>{escape(x)}</li>' for x in c['facts'])
    return f'<template id="e46-component-{c["key"]}"><div class="e46-component-view"><div class="e46-component-visual"><div class="e46-component-visual-head"><span>VR30DDTT / {escape(c["title"])}</span><span>Factory reference</span></div><div class="e46-component-visual-main"><div class="e46-diagram-placeholder">VR30</div><span class="e46-component-stamp">{escape(c["title"])}</span></div></div><div class="e46-component-details"><div class="e46-component-breadcrumb"><button class="e46-component-back" type="button">VR30DDTT / Boost-Air-Fuel</button><span>/</span><span>Component</span></div><h3 class="e46-component-title">{escape(c["title"])}</h3><p class="e46-component-sub">{escape(c["group"])}</p><div class="e46-mini-data"><div><span>Check / diagnose</span><p>{escape(c["check"])}</p></div><div><span>While access is open</span><p>{escape(c["adjacent"])}</p></div></div><ul class="e46-component-parts">{facts}</ul><div class="e46-component-sources">{_refs([("2024 Nissan Z brochure",BROCHURE),("2024 Z owner's manual",OWNER_MANUAL),("Official Nissan parts",PARTS)])}</div></div></div></template>'

def _body():
    specs=''.join(f'<div><span>{k}</span><strong>{v}</strong></div>' for k,v in [("ENGINE","3.0L VR30DDTT"),("POWER","400 hp"),("TORQUE","350 lb-ft"),("DRIVE","Rear-wheel drive"),("DIFF","Mechanical LSD"),("TRIM","Performance")])
    tiles=''.join(_tile(s) for s in SYSTEMS); templates=''.join(_system_template(s) for s in SYSTEMS); components=''.join(_component_template(c) for c in ENGINE_COMPONENTS)
    index=''.join(f'<span class="e46-search-doc" data-doc-type="component" data-system="engine" data-component="{c["key"]}" data-title="{escape(c["title"],quote=True)}" data-search="{escape(_pipes([c["title"],c["group"],c["check"]]+c["facts"]),quote=True)}"></span>' for c in ENGINE_COMPONENTS)
    return f'<div class="e46-home-specs">{specs}</div><div class="e46-index-head"><div><span class="e46-search-kicker">Find anything on this Z</span><p class="e46-index-note">Search a system, symptom, specification or VR30 component. Factory facts are indexed here; exact service work belongs in Nissan service information.</p></div><div><div class="e46-search-shell"><input class="e46-search" type="search" aria-label="Search 2024 Nissan Z workshop" placeholder="boost, intercooler, LSD, Akebono, RAYS, misfire..."><button class="e46-search-clear" type="button">Clear</button></div><div class="e46-search-meta"></div><div class="e46-search-results"></div><div class="e46-didyoumean">Did you mean <button class="e46-spelling" type="button"></button>?</div></div></div><div class="e46-system-grid">{tiles}</div>{index}{templates}{components}'

def _workspace(): return '<div class="e46-workspace-top"><button class="e46-back" type="button">← System index</button><span class="e46-fitment">2024 Nissan Z Performance / RZ34 • record VIN, transmission, build data and modifications in Garage Journey</span></div><div class="e46-workspace-body"></div>'
def _sources():
    sources=[("Factory brochure","2024 Nissan Z brochure",BROCHURE),("Owner reference","2024 Z Owner's Manual",OWNER_MANUAL),("Parts / fitment","Official Nissan Parts",PARTS),("Manual library","Nissan Manuals & Guides",MANUALS)]
    return '<div class="e46-source-strip">'+''.join(f'<a class="e46-source-tile" href="{escape(url,quote=True)}" target="_blank" rel="noopener noreferrer"><span class="e46-source-type">{escape(kind)}</span><strong>{escape(name)}</strong><span>Open source ↗</span></a>' for kind,name,url in sources)+'</div>'

EXTRA_JS = visual_base.EXTRA_JS.replace("const systemsCard=document.querySelector('.card--e46_systems');","const systemsCard=document.querySelector('.card--nissan_systems');").replace("const workspaceCard=document.querySelector('.card--e46_workspace');","const workspaceCard=document.querySelector('.card--nissan_workspace');").replace("showSystem('cooling',false)","showSystem('engine',false)").replace("Cooling → ${item.title}","VR30DDTT → ${item.title}") + r'''
(function(){if(document.querySelector('.gj-floatnav'))return;const nav=document.createElement('nav');nav.className='gj-floatnav';nav.innerHTML='<button type="button" class="gj-nav-back">← Back</button><button type="button" class="gj-nav-home">⌂ Garage Home</button>';document.body.appendChild(nav);const garage=()=>{location.href='/?theme=garage';};nav.querySelector('.gj-nav-back').addEventListener('click',()=>{try{const ref=document.referrer?new URL(document.referrer):null;if(ref&&ref.origin===location.origin){history.back();return;}}catch(error){}garage();});nav.querySelector('.gj-nav-home').addEventListener('click',garage);})();
'''

def build_theme_page(date_str: str | None = None, seed: int | None = None) -> PageContext:
    today=resolve_date(date_str);del seed
    return PageContext(page_title=THEME_CONFIG['page_title'],header_title=THEME_CONFIG['header_title'],header_subtitle=THEME_CONFIG['header_subtitle'],today_str=today.strftime('%A, %B %d, %Y'),cards=[CardItem(card_type='nissan_systems',eyebrow='WORKSHOP INDEX',title='Find It. Then Drill In.',body=_body()),CardItem(card_type='nissan_workspace',eyebrow='WORKSPACE',title='System / Component',body=_workspace()),CardItem(card_type='nissan_library',eyebrow='SOURCE LIBRARY',title='Original References',body=_sources())],footer_text=THEME_CONFIG['footer_text'],metadata={'theme_name':THEME_NAME,'date_key':today.strftime('%m-%d'),'hero_kicker':THEME_CONFIG['hero_kicker'],'hero_summary_pill':THEME_CONFIG['hero_summary_pill'],'extra_css':EXTRA_CSS,'extra_js':EXTRA_JS,'extra_head_html':FONT_HEAD+'<meta name="theme-color" content="#07080a">'})
