from __future__ import annotations

from html import escape

from daily_flyer.models import CardItem, PageContext
from daily_flyer.utils import resolve_date
from daily_flyer.themes import e46_owner_companion_v5 as visual_base

THEME_NAME = "porsche_718_cayman_gt4_2023"
THEME_CONFIG = {
    "page_title": "Garage Journey Workshop — 2023 Porsche 718 Cayman GT4",
    "header_title": "718 CAYMAN GT4 / 982",
    "header_subtitle": "Factory-grounded technical index for the 2023 718 Cayman GT4 — systems, GT chassis, specifications, diagnosis, and original references.",
    "footer_text": "Garage Journey technical reference. Confirm VIN, option codes, brake package, and transmission before applying configuration-specific procedures or parts. Porsche source material remains with Porsche.",
    "hero_kicker": "2023 // 718 CAYMAN GT4 // TYPE 982 // 4.0 FLAT-SIX",
    "hero_summary_pill": "SEARCH • SYSTEM • COMPONENT • SOURCE",
}

PRESS_KIT = "https://newsroom.porsche.com/en/press-kits/718-spyder-cayman-gt4.html"
ENGINE_SOURCE = "https://newsroom.porsche.com/en/press-kits/718-spyder-cayman-gt4/motor-und-performance.html"
CHASSIS_SOURCE = "https://newsroom.porsche.com/en/press-kits/718-spyder-cayman-gt4/fahrwerk-und-regelsysteme.html"
AERO_SOURCE = "https://newsroom.porsche.com/en/press-kits/718-spyder-cayman-gt4/aerodynamik.html"
US_OVERVIEW = "https://newsroom.porsche.com/en_US/products/porsche-718-spyder-cayman-gt4-naturally-aspired-engine-mid-engine.html"
TECH_MANUAL = "https://newsroom.porsche.com/dam/jcr%3A9d46f6de-fbb6-42d8-b474-7295ec4e7e96/PAG_718_Cayman_GT4_EN.pdf"
TECH_PDK = "https://newsroom.porsche.com/dam/jcr%3Ac3c85a80-ec8c-4621-b26c-bd857871e973/PAG_718_Cayman_GT4_PDK_EN.pdf"
PCSS = "https://pcss-tsi.porsche.com/landing/static/US/start"
QSG_2023 = "https://contentful-assets.porsche.com/u1ih0u5p8hpf/6xLgseVbzmiN5H0c5GBe6d/8a7d53b24b051854606b95c846464213/Porsche_MY23_718_QSG.pdf"
RESCUE = "https://files.porsche.com/filestore/download/usa/en-us/porscheserivce-documentsandinformation-rescuedata/default/23a2c2ee-88fe-11ec-80e9-005056bbdc38/Rescue-Data-sheets.pdf"

SYSTEMS = [
    {"key":"engine","index":"4.0","title":"Engine / Induction","subtitle":"Naturally aspirated flat-six","aliases":["motor","flat six","boxer","4 liter","4.0","intake","variocam"],"symptoms":["misfire","rough idle","power loss","oil consumption","engine noise"],"search":"engine motor boxer flat six flat-six 4.0 3995 414 hp 309 lb ft variocam intake injection exhaust 8000 rpm 7600 misfire oil power","primary":"4.0L naturally aspirated six-cylinder boxer","components":["4.0L flat-six","VarioCam Plus","Direct injection","Variable intake","Sport exhaust","Lubrication / oil management"],"facts":["414 hp (US) / 309 kW","309 lb-ft","8,000 rpm maximum engine speed","Peak power at 7,600 rpm"],"sources":[("Factory engine overview",ENGINE_SOURCE),("US GT4 launch technical detail",US_OVERVIEW),("Factory technical data",TECH_MANUAL)]},
    {"key":"cooling","index":"19","title":"Cooling / Thermal","subtitle":"Engine + drivetrain thermal management","aliases":["coolant","radiator","temperature","thermal","water cooling"],"symptoms":["overheat","runs hot","coolant warning","temperature high","coolant leak"],"search":"cooling thermal coolant radiator overheat temperature water cooling engine compartment side intake heat exchanger fan","primary":"Mid-engine thermal-management system","components":["Radiator circuit","Engine coolant","Side air intakes","Engine-bay airflow","Fans / control","Transmission thermal context"],"facts":["Mid-engine package","GT4 sideblades improve engine-compartment airflow","Use PCSS for service procedures and exact circuit detail"],"sources":[("Factory aerodynamics / cooling context",AERO_SOURCE),("Porsche workshop literature",PCSS),("MY23 718 quick-start guide",QSG_2023)]},
    {"key":"transmission","index":"30","title":"Transmission / Differential","subtitle":"6MT or 7-speed PDK / PTV","aliases":["gearbox","manual","6 speed","pdk","dual clutch","differential","lsd","ptv"],"symptoms":["shift issue","clutch","gear noise","driveline vibration","traction"],"search":"transmission gearbox 6 speed manual pdk seven speed dual clutch differential limited slip lsd ptv clutch auto blip gear ratio drivetrain","primary":"Rear-drive GT driveline","components":["6-speed manual","7-speed PDK","Mechanical LSD","Porsche Torque Vectoring","Clutch / dual-clutch","Dynamic drivetrain mounts"],"facts":["6-speed manual available","7-speed PDK available","Mechanical rear differential lock with PTV","Transmission must be recorded on the Garage vehicle"],"sources":[("GT4 launch / manual",US_OVERVIEW),("Factory PDK technical data",TECH_PDK),("Porsche workshop literature",PCSS)]},
    {"key":"chassis","index":"40","title":"GT Chassis / Controls","subtitle":"PASM / PTV / PADM / GT axles","aliases":["suspension","pasm","ptv","padm","front axle","rear axle","alignment","camber","toe"],"symptoms":["pulling","alignment","handling","clunk","damper","traction","steering feel"],"search":"chassis suspension pasm ptv padm front axle rear axle gt3 camber toe ride height anti roll bar alignment ball joint damper strut steering psm esc tc","primary":"Track-bred GT suspension and control systems","components":["Front axle","Rear axle","PASM","Alignment / chassis setup","PTV + LSD","PADM"],"facts":["30 mm lower PASM GT chassis","GT3-derived front-axle architecture","Camber, toe, ride height and anti-roll-bar adjustment","Two-stage PSM deactivation"],"sources":[("Factory chassis / control systems",CHASSIS_SOURCE),("US GT4 chassis summary",US_OVERVIEW),("Factory technical data",TECH_MANUAL)]},
    {"key":"brakes","index":"47","title":"Brakes / Wheels / Tires","subtitle":"GT3-derived brakes / 20-inch fitment","aliases":["brake","rotor","disc","caliper","pccb","wheel","tire","tyre"],"symptoms":["brake vibration","pedal","pad wear","rotor","tire wear","wheel vibration"],"search":"brakes brake rotor disc caliper six piston four piston 380 mm pccb ceramic 410 390 wheel tire tyre 245 35 20 295 30 20","primary":"High-performance GT braking and contact patch","components":["Front steel brakes","Rear steel brakes","PCCB option","20-inch wheels","Front tires","Rear tires"],"facts":["Standard steel discs: 380 mm front/rear","Front: six-piston aluminum monobloc","Rear: four-piston aluminum monobloc","245/35 ZR20 front / 295/30 ZR20 rear"],"sources":[("Factory technical data",TECH_MANUAL),("US brake / tire overview",US_OVERVIEW),("Porsche workshop literature",PCSS)]},
    {"key":"aero","index":"50","title":"Aerodynamics / Body","subtitle":"Wing / diffuser / air curtains","aliases":["aero","wing","diffuser","splitter","spoiler","downforce","air curtain","underbody"],"symptoms":["aero damage","splitter damage","wing damage","underbody damage","cooling airflow"],"search":"aerodynamics aero wing rear wing diffuser splitter spoiler front lip air curtains downforce underbody sideblades intake drag","primary":"Functional GT aerodynamics","components":["Fixed rear wing","Rear diffuser","Front spoiler lip","Air curtains","Underbody guide elements","Side intake blades"],"facts":["Up to 50% more downforce than predecessor","Diffuser contributes about 30% of GT4 rear-axle downforce","Rear wing about 20% more downforce than predecessor"],"sources":[("Factory aerodynamics",AERO_SOURCE),("GT4 launch overview",US_OVERVIEW),("Factory press kit",PRESS_KIT)]},
    {"key":"electrical","index":"90","title":"Electrical / Diagnostics","subtitle":"PSM / PCM / PCSS / vehicle electronics","aliases":["electrical","diagnostics","pcss","porsche tester","psm","pcm","fault","scan","battery"],"symptoms":["warning light","fault code","battery","no start","module","sensor"],"search":"electrical diagnostics pcss tsi tester fault code psm pcm battery sensor obd warning light module no start scan","primary":"Factory diagnostics and vehicle electronics","components":["PCSS workshop info","Virtual Tester access","PSM / ESC / TC","PCM","12V electrical","Sensors / modules"],"facts":["PCSS is Porsche's official workshop-literature portal","Diagnostic access uses Porsche Virtual Tester with approved access","MY23 718 quick-start documentation available"],"sources":[("Porsche PCSS / TSI",PCSS),("MY23 Quick Start Guide",QSG_2023),("Porsche rescue data",RESCUE)]},
]

CHASSIS_COMPONENTS = [
    {"key":"front_axle","title":"Front Axle","group":"GT CHASSIS","aliases":["front suspension","front strut","gt3 front axle","front ball joint"],"symptoms":["front clunk","steering precision","camber","toe","front play"],"check":"Spring-strut hardware, ball-jointed mounts, control links, wheel-bearing/play context and setup values.","adjacent":"Alignment, PASM damper condition, anti-roll-bar setting, brake/tire condition and ride-height setup.","facts":["GT3-derived lightweight spring-strut architecture","Designed for high load and precise steering response","Partially ball-jointed chassis mounting"],"sources":[("Factory chassis detail",CHASSIS_SOURCE),("US chassis summary",US_OVERVIEW),("Workshop procedures",PCSS)]},
    {"key":"rear_axle","title":"Rear Axle","group":"GT CHASSIS","aliases":["rear suspension","rear strut","rear control arm","helper spring"],"symptoms":["rear clunk","traction issue","rear alignment","rear play"],"check":"Rear spring-strut assemblies, helper springs, control links, ball joints, wheel knuckles and subframe condition.","adjacent":"PTV/LSD behavior, PASM, PADM, tire condition and rear alignment.","facts":["Reinforced lightweight rear axle","GT3-derived struts/control arms/subframes","GT4-specific rear wheel-knuckle design"],"sources":[("Factory chassis detail",CHASSIS_SOURCE),("Factory technical data",TECH_MANUAL),("Workshop procedures",PCSS)]},
    {"key":"pasm","title":"PASM GT Suspension","group":"PASM","aliases":["adaptive dampers","pasm sport","damper","shock","30mm lower"],"symptoms":["damper fault","ride harsh","handling change","ride height"],"check":"Damper function/faults, ride-height consistency, control inputs, mounting points and alignment after chassis work.","adjacent":"Alignment, spring-strut hardware, anti-roll-bar setup and tires.","facts":["Standard variable PASM","Two damping settings","30 mm lower than other 718 sports-car variants"],"sources":[("Factory PASM detail",CHASSIS_SOURCE),("US GT4 overview",US_OVERVIEW),("Workshop procedures",PCSS)]},
    {"key":"alignment","title":"Alignment / Setup","group":"GEOMETRY","aliases":["camber","toe","ride height","anti roll bar","alignment","corner balance"],"symptoms":["pulling","uneven tire wear","tramline","handling imbalance"],"check":"Record baseline ride height, camber, toe and anti-roll-bar positions before changing setup; inspect tire wear and chassis play first.","adjacent":"Tire pressures/condition, wheel condition, PASM hardware and track-vs-road setup intent.","facts":["Manual adjustment of camber, toe, ride height and anti-roll bars is part of the GT4 chassis concept","Configuration should be documented as part of the individual Garage vehicle"],"sources":[("Factory chassis detail",CHASSIS_SOURCE),("US GT4 overview",US_OVERVIEW),("Workshop specifications",PCSS)]},
    {"key":"ptv_lsd","title":"PTV + Mechanical LSD","group":"TRACTION","aliases":["ptv","limited slip differential","lsd","diff lock","torque vectoring"],"symptoms":["traction issue","corner exit","differential noise","rear behavior"],"check":"Separate brake-based PTV intervention, mechanical differential behavior, tire differences and alignment/setup before condemning hardware.","adjacent":"Transmission type, rear axle, PSM, tires and PADM.","facts":["PTV is standard","Mechanical limited-slip differential is standard","PTV uses inside-rear-wheel braking to support turn-in while LSD supports traction"],"sources":[("Factory PTV explanation",CHASSIS_SOURCE),("US GT4 overview",US_OVERVIEW),("Workshop diagnostics",PCSS)]},
    {"key":"padm","title":"PADM","group":"DRIVETRAIN MOUNTS","aliases":["active drivetrain mounts","dynamic engine mounts","dynamic transmission mounts","mounts"],"symptoms":["mount fault","drivetrain movement","vibration","load change"],"check":"Fault state, mount response, drivetrain movement and related electrical/control diagnostics before replacement.","adjacent":"Engine/transmission mounts, rear axle behavior, PSM/PTV context and driveline NVH.","facts":["Porsche Active Drivetrain Mounts are standard on GT4","System varies effective mount behavior to balance isolation and dynamic control"],"sources":[("Factory PADM explanation",CHASSIS_SOURCE),("Workshop diagnostics",PCSS),("Factory press kit",PRESS_KIT)]},
]

EXTRA_CSS = visual_base.EXTRA_CSS + r"""
:root{--irish-green:#d5001c;--blue:#d5001c;--teal:#f2b705}
.hero-wrap::before{background:linear-gradient(90deg,#d5001c 0 34%,#fff 34% 67%,#111 67%)}
.hero-kicker,.eyebrow,.e46-work-kicker,.e46-system-index,.e46-component-group{color:#f2b705}
.e46-system:hover,.e46-system:focus-visible,.e46-ref:hover,.e46-component-card:hover,.e46-component-card:focus-visible{background:rgba(213,0,28,.10)}
.e46-system.is-best::after{background:#d5001c}
.e46-search-shell{border-color:rgba(242,183,5,.48);box-shadow:0 0 0 1px rgba(213,0,28,.12),0 16px 50px rgba(0,0,0,.24)}
.e46-schematic-mark{color:#f2b705}.e46-home-specs{display:grid;grid-template-columns:repeat(6,1fr);border-top:1px solid rgba(255,255,255,.15);border-left:1px solid rgba(255,255,255,.15);margin-bottom:28px}.e46-home-specs>div{padding:14px;border-right:1px solid rgba(255,255,255,.15);border-bottom:1px solid rgba(255,255,255,.15)}.e46-home-specs span{display:block;color:#777;font-size:.58rem;font-weight:900;letter-spacing:.12em}.e46-home-specs strong{display:block;margin-top:7px;color:#fff;font-size:.85rem}.e46-fact-list{margin:18px 0 0;padding:0;list-style:none}.e46-fact-list li{padding:8px 0;border-top:1px solid rgba(255,255,255,.11);color:#c7c9ca;font-size:.8rem}.e46-component-stamp{font-size:clamp(2.4rem,6vw,5rem)}
@media(max-width:900px){.e46-home-specs{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.e46-home-specs{grid-template-columns:repeat(2,1fr)}}
"""

def _pipes(items:list[str])->str:return "|".join(items)
def _tile(s):
    attrs=(f'data-key="{escape(s["key"])}" data-title="{escape(s["title"],quote=True)}" data-subtitle="{escape(s["subtitle"],quote=True)}" data-search="{escape(s["search"],quote=True)}" data-items="{escape(_pipes(s["components"]),quote=True)}" data-aliases="{escape(_pipes(s["aliases"]),quote=True)}" data-symptoms="{escape(_pipes(s["symptoms"]),quote=True)}"')
    return f'<button class="e46-system" type="button" {attrs}><div class="e46-system-image e46-schematic"><span class="e46-schematic-mark">{escape(s["index"])}</span></div><div class="e46-system-copy"><span class="e46-system-index">SYSTEM</span><h3>{escape(s["title"])}</h3><p>{escape(s["subtitle"])}</p><span class="e46-open">Open workshop →</span></div></button>'
def _refs(sources):return ''.join(f'<a class="e46-ref" href="{escape(url,quote=True)}" target="_blank" rel="noopener noreferrer"><span>{escape(label)}</span><span>OPEN ↗</span></a>' for label,url in sources)
def _system_template(s):
    components=''.join(f'<span class="e46-component">{escape(c)}</span>' for c in s["components"]);facts=''.join(f'<li>{escape(f)}</li>' for f in s["facts"]);drill=''
    if s["key"]=="chassis":drill='<div class="e46-drill-label">Drill into GT chassis</div><div class="e46-component-nav">'+''.join(f'<button class="e46-component-card" type="button" data-component="{escape(c["key"])}"><span class="e46-component-group">{escape(c["group"])}</span><strong>{escape(c["title"])}</strong><span>{escape(c["check"].split(",")[0])}</span><span class="e46-component-open">→</span></button>' for c in CHASSIS_COMPONENTS)+'</div>'
    return f'<template id="e46-template-{escape(s["key"])}"><div class="e46-workshop"><div class="e46-visual"><div class="e46-visual-head"><span>{escape(s["primary"])}</span><span>Factory-grounded reference</span></div><div class="e46-diagram"><div class="e46-diagram-placeholder">{escape(s["index"])}</div></div><div class="e46-source-credit">Use Porsche PCSS for workshop procedures and exact VIN/configuration-specific information.</div></div><div class="e46-work-details"><span class="e46-work-kicker">2023 718 CAYMAN GT4 / 982</span><h3 class="e46-work-title">{escape(s["title"])}</h3><p class="e46-work-primary">{escape(s["primary"])}</p><div class="e46-component-grid">{components}</div><div class="e46-ref-actions">{_refs(s["sources"])}</div><div class="e46-data-block"><div class="e46-data-label">Pinned factory facts</div><ul class="e46-fact-list">{facts}</ul></div>{drill}</div></div></template>'
def _component_template(c):
    facts=''.join(f'<li>{escape(f)}</li>' for f in c["facts"]);sources=''.join(f'<a class="e46-component-source" href="{escape(url,quote=True)}" target="_blank" rel="noopener noreferrer"><span><small>{escape(label)}</small><strong>Porsche source</strong></span><span>OPEN ↗</span></a>' for label,url in c["sources"])
    return f'<template id="e46-component-{escape(c["key"])}"><div class="e46-component-view"><div class="e46-component-visual"><div class="e46-component-visual-head"><span>GT Chassis / {escape(c["title"])}</span><span>Factory reference</span></div><div class="e46-component-visual-main"><div class="e46-diagram-placeholder">982</div><span class="e46-component-stamp">{escape(c["title"])}</span></div><div class="e46-component-credit">Factory descriptions are indexed here; exact repair instructions and values belong in PCSS for the specific vehicle.</div></div><div class="e46-component-details"><div class="e46-component-breadcrumb"><button class="e46-component-back" type="button">GT Chassis</button><span>/</span><span>Component</span></div><h3 class="e46-component-title">{escape(c["title"])}</h3><p class="e46-component-sub">{escape(c["group"])}</p><div class="e46-mini-data"><div><span>Check / diagnose</span><p>{escape(c["check"])}</p></div><div><span>While access is open</span><p>{escape(c["adjacent"])}</p></div></div><ul class="e46-component-parts">{facts}</ul><div class="e46-component-sources">{sources}</div></div></div></template>'
def _body():
    specs=''.join(f'<div><span>{k}</span><strong>{v}</strong></div>' for k,v in [("ENGINE","4.0 NA flat-six"),("POWER","414 hp"),("REDLINE","8,000 rpm"),("DRIVE","Rear-wheel drive"),("CHASSIS","PASM -30 mm"),("BRAKES","380 mm steel")]);tiles=''.join(_tile(s) for s in SYSTEMS);system_templates=''.join(_system_template(s) for s in SYSTEMS);component_templates=''.join(_component_template(c) for c in CHASSIS_COMPONENTS);component_index=''.join(f'<span class="e46-search-doc" data-doc-type="component" data-system="chassis" data-component="{escape(c["key"])}" data-title="{escape(c["title"],quote=True)}" data-search="{escape(_pipes(c["aliases"]+c["symptoms"]+c["facts"]),quote=True)}"></span>' for c in CHASSIS_COMPONENTS)
    return f'<div class="e46-home-specs">{specs}</div><div class="e46-index-head"><div><span class="e46-search-kicker">Find anything on this GT4</span><p class="e46-index-note">Search a system, symptom, acronym, specification or GT chassis component. Technical facts are indexed from Porsche sources; exact service work routes to PCSS.</p></div><div><div class="e46-search-shell"><input class="e46-search" type="search" aria-label="Search Porsche GT4 workshop" placeholder="PASM, PTV, PCCB, 380 mm, alignment, PDK..."><button class="e46-search-clear" type="button">Clear</button></div><div class="e46-search-meta"></div><div class="e46-search-results"></div><div class="e46-didyoumean">Did you mean <button class="e46-spelling" type="button"></button>?</div></div></div><div class="e46-system-grid">{tiles}</div>{component_index}{system_templates}{component_templates}'
def _workspace():return '<div class="e46-workspace-top"><button class="e46-back" type="button">← System index</button><span class="e46-fitment">2023 718 Cayman GT4 / 982 • record VIN, transmission, brake option and build data in Garage Journey</span></div><div class="e46-workspace-body"></div>'
def _sources():
    sources=[("Factory press kit","Porsche Newsroom — 718 Cayman GT4",PRESS_KIT),("Factory technical data","718 Cayman GT4 technical PDF",TECH_MANUAL),("MY23 vehicle guide","2023 718 Quick Start Guide",QSG_2023),("Workshop literature / diagnosis","Porsche PCSS / TSI",PCSS),("Emergency layout","Porsche 718 GT4 rescue data",RESCUE)]
    return '<div class="e46-source-strip">'+''.join(f'<a class="e46-source-tile" href="{escape(url,quote=True)}" target="_blank" rel="noopener noreferrer"><span class="e46-source-type">{escape(kind)}</span><strong>{escape(name)}</strong><span>Open source ↗</span></a>' for kind,name,url in sources)+'</div>'

EXTRA_JS = visual_base.EXTRA_JS.replace("const systemsCard=document.querySelector('.card--e46_systems');","const systemsCard=document.querySelector('.card--porsche_systems');").replace("const workspaceCard=document.querySelector('.card--e46_workspace');","const workspaceCard=document.querySelector('.card--porsche_workspace');").replace("showSystem('cooling',false)","showSystem('chassis',false)").replace("Cooling → ${item.title}","GT Chassis → ${item.title}")

def build_theme_page(date_str:str|None=None,seed:int|None=None)->PageContext:
    today=resolve_date(date_str);del seed
    return PageContext(page_title=THEME_CONFIG["page_title"],header_title=THEME_CONFIG["header_title"],header_subtitle=THEME_CONFIG["header_subtitle"],today_str=today.strftime("%A, %B %d, %Y"),cards=[CardItem(card_type="porsche_systems",eyebrow="WORKSHOP INDEX",title="Find It. Then Drill In.",body=_body()),CardItem(card_type="porsche_workspace",eyebrow="WORKSPACE",title="System / Component",body=_workspace()),CardItem(card_type="porsche_library",eyebrow="SOURCE LIBRARY",title="Original References",body=_sources())],footer_text=THEME_CONFIG["footer_text"],metadata={"theme_name":THEME_NAME,"date_key":today.strftime("%m-%d"),"hero_kicker":THEME_CONFIG["hero_kicker"],"hero_summary_pill":THEME_CONFIG["hero_summary_pill"],"extra_css":EXTRA_CSS,"extra_js":EXTRA_JS,"extra_head_html":'<meta name="theme-color" content="#111111">'})
