const test=require('node:test'),assert=require('node:assert/strict');
const E=require('./suggestions.js');
const cfg={enabled:true,supabase_url:'https://example-project.supabase.co',publishable_key:'sb_publishable_test_public_key_only',participant_contact:'pilot@example.org',retention_notice:'A defined retention and deletion notice is required.',policy_version:'pilot-2026-10-08'};
test('disabled and incomplete configuration stays closed',()=>{for(const c of [{},null,{...cfg,enabled:false},{...cfg,participant_contact:''},{...cfg,retention_notice:''}])assert.equal(E.validConfig(c),false);assert.equal(E.validConfig(cfg),true);});
test('secret keys and untrusted endpoints are rejected',()=>{for(const c of [{...cfg,publishable_key:'sb_secret_never_public'},{...cfg,publishable_key:'eyJservice_role'},{...cfg,supabase_url:'https://evil.org'},{...cfg,supabase_url:'http://example-project.supabase.co'},{...cfg,supabase_url:'https://example-project.supabase.co.evil.org'}])assert.equal(E.validConfig(c),false);});
test('all user text is escaped and unknown issue links suppressed',()=>{const s={id:'test',title:'<img src=x onerror=alert(1)>',problem:'<script>bad</script>',desired_outcome:'hello',review_label:'" onclick=evil',version:1,votes:3,related_issue:'javascript:alert(1)'};const html=E.boardMarkup([s],[],true);assert.doesNotMatch(html,/<img|<script|href="javascript/);assert.match(html,/&lt;img/);});
test('empty board has no fabricated approvals or supporters',()=>{const html=E.boardMarkup([],[],false);assert.match(html,/No published suggestions/);assert.doesNotMatch(html,/QA fixture|pilot supporters/);});
test('ranking is deterministic and does not mutate input',()=>{const rows=[{id:'b',votes:2,published_at:'2026-10-08'},{id:'a',votes:5,published_at:'2026-10-08'}];assert.equal(E.sorted(rows,'votes')[0].id,'a');assert.equal(rows[0].id,'b');});
test('related links only target canonical known issues',()=>{assert.equal(E.related('HLLV-999',[]),'');assert.match(E.related('HLLV-007',[{id:'HLLV-007',title:'Controls'}]),/href="#HLLV-007"/);});
